//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Covid1920200603125049_dbEntities : DbContext
    {
        public Covid1920200603125049_dbEntities()
            : base("name=Covid1920200603125049_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CountryWiseCas> CountryWiseCases { get; set; }
        public virtual DbSet<CountryWiseTotalCasesByDay> CountryWiseTotalCasesByDays { get; set; }
        public virtual DbSet<NoofDeathByDay> NoofDeathByDays { get; set; }
        public virtual DbSet<DailyNewCase> DailyNewCases { get; set; }
    }
}
