//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoofDeathByDay
    {
        public int DeathId { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<long> TotalDeath { get; set; }
    }
}
